CREATE TABLE "authors" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" text NOT NULL,
  "bio" text
);

CREATE TABLE "books" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "title" text NOT NULL,
  "isbn" bigint,
  "description" text,
  "location_id" integer,
  "owner_id" integer,
  "cover_url" text,
  "created_date" timestamp with time zone
);

CREATE TABLE "tags" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "label" text,
  "description" text
);

CREATE TABLE "locations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" text,
  "notes" text,
  "place_id" integer
);

CREATE TABLE "places" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" text,
  "notes" text
);

CREATE TABLE "books_authors" (
  "books_id" integer,
  "authors_id" integer,
  PRIMARY KEY ("books_id", "authors_id")
);

ALTER TABLE "books_authors" ADD FOREIGN KEY ("books_id") REFERENCES "books" ("id");

ALTER TABLE "books_authors" ADD FOREIGN KEY ("authors_id") REFERENCES "authors" ("id");


CREATE TABLE "books_tags" (
  "books_id" integer,
  "tags_id" integer,
  PRIMARY KEY ("books_id", "tags_id")
);

ALTER TABLE "books_tags" ADD FOREIGN KEY ("books_id") REFERENCES "books" ("id");

ALTER TABLE "books_tags" ADD FOREIGN KEY ("tags_id") REFERENCES "tags" ("id");

ALTER TABLE "books" ADD FOREIGN KEY ("location_id") REFERENCES "locations" ("id");

ALTER TABLE "books" ADD FOREIGN KEY ("owner_id") REFERENCES "owners" ("id");

ALTER TABLE "locations" ADD FOREIGN KEY ("place_id") REFERENCES "places" ("id");
